apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    app: {{ include "mysql.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 16
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - info
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: {{ include "mysql.getdbserviceurl" . }}
            - name: FLYWAY_USER
              value: {{ .Values.job.env.FLYWAY_USER }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.fullname" . }}
                  key: password
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: {{ .Values.job.env.FLYWAY_PLACEHOLDER_REPLACEMENT | quote}}
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mysql.fullname" . }}
                  key: spring.datasource.username
            - name: FLYWAY_PLACEHOLDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.fullname" . }}
                  key: password
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          configMap:
            name: {{ include "mysql.fullname" . }}
      restartPolicy: Never