apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "api.fullname" . }}
  name: {{ include "api.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: {{ include "api.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
     {{- if ge .Values.deployment.replicaCount 5.0 }}
      maxUnavailable: 2
     {{- else }}
      maxUnavailable: 0
     {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "api.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: PAGE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: PAGE_CONTENT
            - name: SPRING_DATASOURCE_URL
              value: {{ include "api.getdbserviceurl" . }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote}}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: password
            {{- with .Values.env }}
            - name: DEBUG
              value: {{ .DEBUG | quote}}
            - name: LOGGING_FILE_NAME
              value: {{ .LOGGING_FILE_NAME | quote}}
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: {{ .LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .LOGGING_LEVEL_ROOT }}
            {{- end }}
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
          volumeMounts:
            - name: node-dir
              mountPath: /{{ .Release.Namespace }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.readinessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
      volumes:
        - name: node-dir
          hostPath:
            path: /{{ .Release.Namespace }}