apiVersion: v1
kind: Pod
metadata:
  labels:
    app: contracts-pages-api
    helm: test
  name: contract-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: postman-test
      image: dellcloud/newman:latest #derived from postman/newman
      command: ["newman","run", "https://cloud-native-labs.s3.ap-south-1.amazonaws.com/J21/labguide/pages-testsuite.json" ]
      args:
        - --env-var
        - BASE_URL={{ .Release.Name }}-{{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8080
  restartPolicy: Never