apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dbconnect-pages-api
    helm: test
  name: pages-test-dbconnect-passtest
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - image: mysql:8.0
      name: pages-test-pass
      imagePullPolicy: Always
      command: ["/bin/bash"]
      args: ["-c", "while true; do (mysql -u root -h pages-mysql pages -ppassword  -e 'show tables;' > logs.txt);count=$(cat logs.txt | grep '[p]ages' | wc -l);if [[ $count -gt 0 ]]; then echo 'Found'; exit 0;else echo 'Not Found';exit 1;fi;done"]
  restartPolicy: Never